### ISSUE TITLE
msrest.exceptions.ValidationError: Parameter 'Deployment.properties' can not be None.

### ISSUE THREAD

**Issue by ChrisStonebackTR** [Azure-Samples/resource-manager-python-template-deployment#7]
When executing azure_deployment.py, I get this error : "msrest.exceptions.ValidationError: Parameter 'Deployment.properties' can not be None."   deployment_properties variable  looks good with valid mode, template and parameters.   Any suggestions?

```
        deployment_properties = {
            'mode': DeploymentMode.incremental,
            'template': template,
            'parameters': parameters
        }

        deployment_async_operation = self.client.deployments.create_or_update(
            self.resource_group,
            'azure-sample',
            deployment_properties
        )
```

```
Traceback (most recent call last):
  File "c:/REDACTED/azure_deployment.py", line 27, in <module>
    my_deployment = deployer.deploy()
  File "c:\REDACTED\deployer.py", line 178, in deploy
    deployment_properties
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python36\lib\site-packages\azure\mgmt\resource\resources\v2019_10_01\operations\_deployments_operations.py", line 2654, in create_or_update
    **operation_config
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python36\lib\site-packages\azure\mgmt\resource\resources\v2019_10_01\operations\_deployments_operations.py", line 2595, in _create_or_update_initial
    body_content = self._serialize.body(parameters, 'Deployment')
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python36\lib\site-packages\msrest\serialization.py", line 586, in body
    raise errors[0]
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python36\lib\site-packages\msrest\serialization.py", line 223, in validate
    Serializer.validate(value, debug_name, **self._validation.get(attr_name, {}))
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python36\lib\site-packages\msrest\serialization.py", line 688, in validate
    raise ValidationError("required", name, True)
msrest.exceptions.ValidationError: Parameter 'Deployment.properties' can not be None.
```

**Comment by serbaniuliuscezar** [comment]
I also have this issue. This is definitely  caused by version 9.0.0 of the azure-mgmt-resource module. Version 8.0.1 works fine.

When I upgraded I got the error above. I checked all the documentation I could find but I can't seem to find anything related to the properties parameter.

```
pip3 list | grep azure-mgmt-resource
azure-mgmt-resource                   9.0.0
```
```

**Comment by ChrisStonebackTR** [comment]
I was able to get it to work with this change:


```
from azure.mgmt.resource.resources.models import Deployment
from azure.mgmt.resource.resources.models import DeploymentProperties



        deployment_properties = DeploymentProperties(mode=DeploymentMode.incremental, template=template, parameters=parameters)
        deployment_async_operation = self.client.deployments.create_or_update(
            self.resource_group,
            'azure-sample',
            Deployment(properties=deployment_properties)
        )
        deployment_async_operation.wait()
```

**Comment by serbaniuliuscezar** [comment]
@ChrisStonebackTR Nice find. Do you think a PR is in order? I think people will run into this issue when they upgrade their package version.

**Comment by mvitor** [comment]
God! Thanks for this. This out of date python sdk samples and multiple apis versions drive me crazy sometimes.
